# from base image ubuntu latest
FROM ubuntu:20.04

# # update package list and install python and pip
RUN apt-get update && apt-get install -y python3 python3-pip && apt-get install -y gcc

# set workspace
WORKDIR /workspace

# install requirements
COPY requirements.txt /workspace/
RUN pip install --no-cache-dir -r requirements_light_base.txt -i https://mirrors.aliyun.com/pypi/simple/